# SubscriptionCreated
POST http://127.0.0.1:8000/register/ddd/
Content-Type: application/json

{
  "resp_path":"llllhhh"
}



###
GET http://127.0.0.1:8000/getcards/733585869/?resp_path=5e55159e2b23da3ecf879abf/c/733585869
Content-Type: application/json
{}

###
###
POST http://127.0.0.1:8000/like/ddd/
Content-Type: application/json

{
    "str_to_parse":"{\"type\":\"like\",\"card_id\":3}",
    "resp_path":"llllhhh"
}

###

POST http://127.0.0.1:8000/like/ddd/
Content-Type: application/json

{
    "str_to_parse":"{\"type\":\"dislike\",\"card_id\":1}",
    "resp_path":"llllhhh"
}

###

POST http://127.0.0.1:8000/book_evening/ddd/
Content-Type: application/json

{
    "str_to_parse":"{\"card_id\":1,\"date\":\"2020-03-05\"}",
    "resp_path":"llllhhh"
}

###
PUT http://127.0.0.1:8000/updprefs/ddd/
Content-Type: application/json

{
    "str_to_parse":"{\"cat_id\":3, \"action\": \"on\"}",
    "resp_path":"llllhhh"
}



###
PUT http://91.245.227.206/updprefs/ddd/
Content-Type: application/json

{
    "str_to_parse":"{\"cat_id\":1, \"action\": \"on\"}",
    "resp_path":"llllhhh"
}

###

GET http://127.0.0.1:8000/getmycats/ddd/?resp_path=llllhhh
Content-Type: application/json

{
}

###
GET http://91.245.227.206/getmycats/ddd/?resp_path=llllhhh



###
GET http://127.0.0.1:8000/getbtns/ddd/?resp_path=llllhhh

###
GET http://91.245.227.206/getbtns/ddd/?resp_path=llllhhh

###
###
GET http://127.0.0.1:8000/resetprefs/ddd/?resp_path=llllhhh

###
GET http://127.0.0.1:8000/sendeveningreminder/

###
GET http://127.0.0.1:8000/sendaddactivity/


###
GET http://127.0.0.1:8000/getplans/ddd/?resp_path=llllhhh

###
GET http://127.0.0.1:8000/sendaddactivity/

###
GET http://127.0.0.1:8000/getweekendschedule/ddd/?resp_path=llllhhh


###
GET http://127.0.0.1:8000/getcardsondate/733585869/?resp_path=5e55159e2b23da3ecf879abf/c/733585869

{
    "str_to_parse":"{\"type\":\"get_on_date\",\"date\":\"2020-03-05\"}"
}

###
GET http://91.245.227.206/getweekendschedule/733585869/?resp_path=5e55159e2b23da3ecf879abf/c/733585869




###
GET http://91.245.227.206/testallcards/


###
GET http://91.245.227.206/getplans/733585869/?resp_path=5e55159e2b23da3ecf879abf/c/733585869



###
GET http://91.245.227.206/sendeveningreminder/

###
GET http://91.245.227.206/sendaddactivity/
###



