# SubscriptionCreated
POST http://127.0.0.1:8000/register/ddd/?resp_path=llllhhh
Content-Type: application/json
{}



###
GET http://127.0.0.1:8000/getcards/ddd/?resp_path=llllhhh
Content-Type: application/json
{}

###
###
POST http://127.0.0.1:8000/like/ddd/?resp_path=llllhhh
Content-Type: application/json

{
    "str_to_parse":"{\"type\":\"like\",\"card_id\":1}"
}

###

POST http://127.0.0.1:8000/like/ddd/?resp_path=llllhhh
Content-Type: application/json

{
    "str_to_parse":"{\"type\":\"dislike\",\"card_id\":1}"
}

###
PUT http://127.0.0.1:8000/updprefs/ddd/?resp_path=llllhhh
Content-Type: application/json

{
    "str_to_parse":"{\"cat_id\":3, \"action\": \"on\"}"
}



###
PUT http://91.245.227.206/updprefs/ddd/?resp_path=llllhhh
Content-Type: application/json

{
    "str_to_parse":"{\"cat_id\":1, \"action\": \"on\"}"
}

###

GET http://127.0.0.1:8000/getmycats/ddd/?resp_path=llllhhh
Content-Type: application/json

{
}

###
GET http://91.245.227.206/getmycats/ddd/?resp_path=llllhhh



###
GET http://127.0.0.1:8000/getbtns/ddd/?resp_path=llllhhh

###
GET http://91.245.227.206/getbtns/ddd/?resp_path=llllhhh

###
###
GET http://127.0.0.1:8000/resetprefs/ddd/?resp_path=llllhhh

###
