# SubscriptionCreated
POST http://127.0.0.1:8000/register/ddd/
Content-Type: application/json
{}



###
GET http://127.0.0.1:8000/getcards/ddd/
Content-Type: application/json
{}

###
###
POST http://127.0.0.1:8000/like/ddd/
Content-Type: application/json

{
    "str_to_parse":"{\"type\":\"like\",\"card_id\":1}"
}

###

POST http://127.0.0.1:8000/like/ddd/
Content-Type: application/json

{
    "str_to_parse":"{\"type\":\"dislike\",\"card_id\":1}"
}

###
PUT http://127.0.0.1:8000/updprefs/ddd/
Content-Type: application/json

{
    "str_to_parse":"{\"is_kulinar\":true}"
}



###
PUT http://91.245.227.206/updprefs/ddd/
Content-Type: application/json

{
    "str_to_parse":"{\"is_kulinar\":true}"
}

###

